### ISSUE TITLE
Rhubarb scripting language

### ISSUE THREAD

**Issue by Faolan-Rad** [RhubarbVR/RhubarbVR_Old#27]
The plan is to develop a typescript like language that can be complied into IL code to run along side with the engine while still being secure. The other part is to make it able to be turned into a visual form of the same script.

**Comment by Reiko9** [comment]
After skimming through this video I had the idea that the Text language could be made up of a bunch of linked "nodes"
https://www.youtube.com/watch?v=_tma9msTfpM

Basically a node would be defined sort of like a function, but unlike a function support multiple outputs, the inputs and outputs of nodes could be wired together into a network, but making an easy to read syntax for this mapping is difficult.  

(A conventional Typescript interpreter can of course handle the code within nodes, but linking of code blocks would probably need custom coded)

(By defining portmap it will lead to less confusion, because this uses the pipe symbol to route data like in bash not a binary OR)
(at least this is simple to understand and not as complex to parse as the ==> arrow)

portmap: 
Quadratic_formula:x | multiplier:a
Quadratic_formula:x | multiplier:b  
end portmap;

**Comment by iamgreaser** [comment]
Some thoughts.

**Do you want this to be primarily visual, or primarily textual?**

That will shape both representations of the language:

* If primarily visual, then one may want to be able to position nodes arbitrarily. It's likely that the textual form will follow some kind of DAG rather than a strict tree, and the cleanest way I can think of here is to go with something that looks a little assembly-ish or BASIC-ish.
* If primarily textual, then placement of nodes into the visual space is likely going to be programmatic and somewhat along the lines of the GraphViz `dot` program. Also, node instances will most likely need to have reasonable names.

Here's what I think:

* Visual representation should be the primary representation.
* The textual representation should at least be able to survive being beaten up via Git and making its way through several merges as well as merge conflicts.
* As a corollary, the textual representation should also be editable without too much pain.
* Nodes should be nameable anyway (partly to help with "documentation"), although initially the nodes should have an autogenerated name consisting of the node type and a sequential number for said node type.

Admittedly I've got LogiX in my head, but there's potential to go with a substantially different model.

**Comment by Earthmark** [comment]
When you parse a language your making a dependency graph anyways, if the node form is the logical graph the compiler constructed from the textual form, that's an easy bidirectional path.

Granted converting it back to text and having it readable are going to be odd. It'll likely be like the text has a constant linter running over it, so a bit like working with go.
